# Programmas prasību specifikācija (PPS)

## Mērķis
Šis projekts demonstrē vienkāršu IT arodbiedrības datu skatīšanu. Lietotājs var redzēt sarakstu ar biedriem un uzdevumiem. Projekts pastāv kā mācību piemērs praksē.

## Galvenie lietotāji
- Praktikants
- IT arodbiedrības biedrs

## Funkcionalitāte
- Lietotājs var skatīt datu sarakstu lapā.
- Šobrīd dati ir statiski, bet nākotnē varētu pievienot dinamisku datu bāzi vai formu datu ievadei.
